/**
 * DMG
 * Copyright (C) 2020 David Jolly
 *
 * DMG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DMG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef DMG_TOOL_SYNTAX_TYPE_H_
#define DMG_TOOL_SYNTAX_TYPE_H_

#include "../include/common.h"
#include "../include/syntax.h"

static const char *DIRECTIVE_STR[] = {
	DIRECTIVE_DELIMITER "bank", /* DIRECTIVE_BANK */
	DIRECTIVE_DELIMITER "db", /* DIRECTIVE_DATA */
	DIRECTIVE_DELIMITER "org", /* DIRECTIVE_ORIGIN */
	"", /* DIRECTIVE_MAX */
	};

static const char *HEADER_STR[] = {
	"hdr_entry" LABEL_PREFIX, /* HEADER_ENTRY */
	"hdr_logo" LABEL_PREFIX, /* HEADER_LOGO */
	"hdr_title" LABEL_PREFIX, /* HEADER_TITLE */
	"hdr_manuf" LABEL_PREFIX, /* HEADER_MANUFACTURER */
	"hdr_cgb" LABEL_PREFIX, /* HEADER_COLOR_GAMEBOY */
	"hdr_lic" LABEL_PREFIX, /* HEADER_LICENSEE */
	"hdr_sgb" LABEL_PREFIX, /* HEADER_SUPER_GAMEBOY */
	"hdr_map" LABEL_PREFIX, /* HEADER_MAPPER */
	"hdr_rom" LABEL_PREFIX, /* HEADER_ROM */
	"hdr_ram" LABEL_PREFIX, /* HEADER_RAM */
	"hdr_dest" LABEL_PREFIX, /* HEADER_DESTINATION */
	"hdr_lic_old" LABEL_PREFIX, /* HEADER_LICENSEE_OLD */
	"hdr_ver" LABEL_PREFIX, /* HEADER_VERSION */
	"hdr_sum" LABEL_PREFIX, /* HEADER_CHECKSUM */
	"hdr_sum_glb" LABEL_PREFIX, /* HEADER_CHECKSUM_GLOBAL */
	"", /* HEADER_MAX */
	};

static const dmg_tool_instruction_t INSTRUCTION[] = {
	{ INSTRUCTION_NOP, OPERAND_NONE}, /* 0x00 */
	{ INSTRUCTION_LD_BC_U16, OPERAND_WORD},
	{ INSTRUCTION_LD_BC_IND_A, OPERAND_NONE},
	{ INSTRUCTION_INC_BC, OPERAND_NONE},
	{ INSTRUCTION_INC_B, OPERAND_NONE},
	{ INSTRUCTION_DEC_B, OPERAND_NONE},
	{ INSTRUCTION_LD_B_U8, OPERAND_BYTE},
	{ INSTRUCTION_RLCA, OPERAND_NONE},
	{ INSTRUCTION_LD_U16_IND_SP, OPERAND_WORD}, /* 0x08 */
	{ INSTRUCTION_ADD_HL_BC, OPERAND_NONE},
	{ INSTRUCTION_LD_A_BC_IND, OPERAND_NONE},
	{ INSTRUCTION_DEC_BC, OPERAND_NONE},
	{ INSTRUCTION_INC_C, OPERAND_NONE},
	{ INSTRUCTION_DEC_C, OPERAND_NONE},
	{ INSTRUCTION_LD_C_U8, OPERAND_BYTE},
	{ INSTRUCTION_RRCA, OPERAND_NONE},
	{ INSTRUCTION_STOP, OPERAND_BYTE}, /* 0x10 */
	{ INSTRUCTION_LD_DE_U16, OPERAND_WORD},
	{ INSTRUCTION_LD_DE_IND_A, OPERAND_NONE},
	{ INSTRUCTION_INC_DE, OPERAND_NONE},
	{ INSTRUCTION_INC_D, OPERAND_NONE},
	{ INSTRUCTION_DEC_D, OPERAND_NONE},
	{ INSTRUCTION_LD_D_U8, OPERAND_BYTE},
	{ INSTRUCTION_RLA, OPERAND_NONE},
	{ INSTRUCTION_JR_I8, OPERAND_BYTE}, /* 0x18 */
	{ INSTRUCTION_ADD_HL_DE, OPERAND_NONE},
	{ INSTRUCTION_LD_A_DE_IND, OPERAND_NONE},
	{ INSTRUCTION_DEC_DE, OPERAND_NONE},
	{ INSTRUCTION_INC_E, OPERAND_NONE},
	{ INSTRUCTION_DEC_E, OPERAND_NONE},
	{ INSTRUCTION_LD_E_U8, OPERAND_BYTE},
	{ INSTRUCTION_RRA, OPERAND_NONE},
	{ INSTRUCTION_JR_NZ_I8, OPERAND_BYTE}, /* 0x20 */
	{ INSTRUCTION_LD_HL_U16, OPERAND_WORD},
	{ INSTRUCTION_LD_HL_IND_INC_A, OPERAND_NONE},
	{ INSTRUCTION_INC_HL, OPERAND_NONE},
	{ INSTRUCTION_INC_H, OPERAND_NONE},
	{ INSTRUCTION_DEC_H, OPERAND_NONE},
	{ INSTRUCTION_LD_H_U8, OPERAND_BYTE},
	{ INSTRUCTION_DAA, OPERAND_NONE},
	{ INSTRUCTION_JR_Z_I8, OPERAND_BYTE}, /* 0x28 */
	{ INSTRUCTION_ADD_HL_HL, OPERAND_NONE},
	{ INSTRUCTION_LD_A_HL_IND_INC, OPERAND_NONE},
	{ INSTRUCTION_DEC_HL, OPERAND_NONE},
	{ INSTRUCTION_INC_L, OPERAND_NONE},
	{ INSTRUCTION_DEC_L, OPERAND_NONE},
	{ INSTRUCTION_LD_L_U8, OPERAND_BYTE},
	{ INSTRUCTION_CPL, OPERAND_NONE},
	{ INSTRUCTION_JR_NC_I8, OPERAND_BYTE}, /* 0x30 */
	{ INSTRUCTION_LD_SP_U16, OPERAND_WORD},
	{ INSTRUCTION_LD_HL_IND_DEC_A, OPERAND_NONE},
	{ INSTRUCTION_INC_SP, OPERAND_NONE},
	{ INSTRUCTION_INC_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_DEC_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_U8, OPERAND_BYTE},
	{ INSTRUCTION_SCF, OPERAND_NONE},
	{ INSTRUCTION_JR_C_I8, OPERAND_BYTE}, /* 0x38 */
	{ INSTRUCTION_ADD_HL_SP, OPERAND_NONE},
	{ INSTRUCTION_LD_A_HL_IND_DEC, OPERAND_NONE},
	{ INSTRUCTION_DEC_SP, OPERAND_NONE},
	{ INSTRUCTION_INC_A, OPERAND_NONE},
	{ INSTRUCTION_DEC_A, OPERAND_NONE},
	{ INSTRUCTION_LD_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_CCF, OPERAND_NONE},
	{ INSTRUCTION_LD_B_B, OPERAND_NONE}, /* 0x40 */
	{ INSTRUCTION_LD_B_C, OPERAND_NONE},
	{ INSTRUCTION_LD_B_D, OPERAND_NONE},
	{ INSTRUCTION_LD_B_E, OPERAND_NONE},
	{ INSTRUCTION_LD_B_H, OPERAND_NONE},
	{ INSTRUCTION_LD_B_L, OPERAND_NONE},
	{ INSTRUCTION_LD_B_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_B_A, OPERAND_NONE},
	{ INSTRUCTION_LD_C_B, OPERAND_NONE}, /* 0x48 */
	{ INSTRUCTION_LD_C_C, OPERAND_NONE},
	{ INSTRUCTION_LD_C_D, OPERAND_NONE},
	{ INSTRUCTION_LD_C_E, OPERAND_NONE},
	{ INSTRUCTION_LD_C_H, OPERAND_NONE},
	{ INSTRUCTION_LD_C_L, OPERAND_NONE},
	{ INSTRUCTION_LD_C_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_C_A, OPERAND_NONE},
	{ INSTRUCTION_LD_D_B, OPERAND_NONE}, /* 0x50 */
	{ INSTRUCTION_LD_D_C, OPERAND_NONE},
	{ INSTRUCTION_LD_D_D, OPERAND_NONE},
	{ INSTRUCTION_LD_D_E, OPERAND_NONE},
	{ INSTRUCTION_LD_D_H, OPERAND_NONE},
	{ INSTRUCTION_LD_D_L, OPERAND_NONE},
	{ INSTRUCTION_LD_D_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_D_A, OPERAND_NONE},
	{ INSTRUCTION_LD_E_B, OPERAND_NONE}, /* 0x58 */
	{ INSTRUCTION_LD_E_C, OPERAND_NONE},
	{ INSTRUCTION_LD_E_D, OPERAND_NONE},
	{ INSTRUCTION_LD_E_E, OPERAND_NONE},
	{ INSTRUCTION_LD_E_H, OPERAND_NONE},
	{ INSTRUCTION_LD_E_L, OPERAND_NONE},
	{ INSTRUCTION_LD_E_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_E_A, OPERAND_NONE},
	{ INSTRUCTION_LD_H_B, OPERAND_NONE}, /* 0x60 */
	{ INSTRUCTION_LD_H_C, OPERAND_NONE},
	{ INSTRUCTION_LD_H_D, OPERAND_NONE},
	{ INSTRUCTION_LD_H_E, OPERAND_NONE},
	{ INSTRUCTION_LD_H_H, OPERAND_NONE},
	{ INSTRUCTION_LD_H_L, OPERAND_NONE},
	{ INSTRUCTION_LD_H_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_H_A, OPERAND_NONE},
	{ INSTRUCTION_LD_L_B, OPERAND_NONE}, /* 0x68 */
	{ INSTRUCTION_LD_L_C, OPERAND_NONE},
	{ INSTRUCTION_LD_L_D, OPERAND_NONE},
	{ INSTRUCTION_LD_L_E, OPERAND_NONE},
	{ INSTRUCTION_LD_L_H, OPERAND_NONE},
	{ INSTRUCTION_LD_L_L, OPERAND_NONE},
	{ INSTRUCTION_LD_L_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_L_A, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_B, OPERAND_NONE}, /* 0x70 */
	{ INSTRUCTION_LD_HL_IND_C, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_D, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_E, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_H, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_L, OPERAND_NONE},
	{ INSTRUCTION_HALT, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_IND_A, OPERAND_NONE},
	{ INSTRUCTION_LD_A_B, OPERAND_NONE}, /* 0x78 */
	{ INSTRUCTION_LD_A_C, OPERAND_NONE},
	{ INSTRUCTION_LD_A_D, OPERAND_NONE},
	{ INSTRUCTION_LD_A_E, OPERAND_NONE},
	{ INSTRUCTION_LD_A_H, OPERAND_NONE},
	{ INSTRUCTION_LD_A_L, OPERAND_NONE},
	{ INSTRUCTION_LD_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_LD_A_A, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_B, OPERAND_NONE}, /* 0x80 */
	{ INSTRUCTION_ADD_A_C, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_D, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_E, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_H, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_L, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_A, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_B, OPERAND_NONE}, /* 0x88 */
	{ INSTRUCTION_ADC_A_C, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_D, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_E, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_H, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_L, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_ADC_A_A, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_B, OPERAND_NONE}, /* 0x90 */
	{ INSTRUCTION_SUB_A_C, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_D, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_E, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_H, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_L, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_A, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_B, OPERAND_NONE}, /* 0x98 */
	{ INSTRUCTION_SBC_A_C, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_D, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_E, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_H, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_L, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_A, OPERAND_NONE},
	{ INSTRUCTION_AND_A_B, OPERAND_NONE}, /* 0xa0 */
	{ INSTRUCTION_AND_A_C, OPERAND_NONE},
	{ INSTRUCTION_AND_A_D, OPERAND_NONE},
	{ INSTRUCTION_AND_A_E, OPERAND_NONE},
	{ INSTRUCTION_AND_A_H, OPERAND_NONE},
	{ INSTRUCTION_AND_A_L, OPERAND_NONE},
	{ INSTRUCTION_AND_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_AND_A_A, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_B, OPERAND_NONE}, /* 0xa8 */
	{ INSTRUCTION_XOR_A_C, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_D, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_E, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_H, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_L, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_A, OPERAND_NONE},
	{ INSTRUCTION_OR_A_B, OPERAND_NONE}, /* 0xb0 */
	{ INSTRUCTION_OR_A_C, OPERAND_NONE},
	{ INSTRUCTION_OR_A_D, OPERAND_NONE},
	{ INSTRUCTION_OR_A_E, OPERAND_NONE},
	{ INSTRUCTION_OR_A_H, OPERAND_NONE},
	{ INSTRUCTION_OR_A_L, OPERAND_NONE},
	{ INSTRUCTION_OR_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_OR_A_A, OPERAND_NONE},
	{ INSTRUCTION_CP_A_B, OPERAND_NONE}, /* 0xb8 */
	{ INSTRUCTION_CP_A_C, OPERAND_NONE},
	{ INSTRUCTION_CP_A_D, OPERAND_NONE},
	{ INSTRUCTION_CP_A_E, OPERAND_NONE},
	{ INSTRUCTION_CP_A_H, OPERAND_NONE},
	{ INSTRUCTION_CP_A_L, OPERAND_NONE},
	{ INSTRUCTION_CP_A_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_CP_A_A, OPERAND_NONE},
	{ INSTRUCTION_RET_NZ, OPERAND_NONE}, /* 0xc0 */
	{ INSTRUCTION_POP_BC, OPERAND_NONE},
	{ INSTRUCTION_JP_NZ_U16, OPERAND_WORD},
	{ INSTRUCTION_JP_U16, OPERAND_WORD},
	{ INSTRUCTION_CALL_NZ_U16, OPERAND_WORD},
	{ INSTRUCTION_PUSH_BC, OPERAND_NONE},
	{ INSTRUCTION_ADD_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_00, OPERAND_NONE},
	{ INSTRUCTION_RET_Z, OPERAND_NONE}, /* 0xc8 */
	{ INSTRUCTION_RET, OPERAND_NONE},
	{ INSTRUCTION_JP_Z_U16, OPERAND_WORD},
	{ INSTRUCTION_EXTENDED_PREFIX, OPERAND_NONE},
	{ INSTRUCTION_CALL_Z_U16, OPERAND_WORD},
	{ INSTRUCTION_CALL_U16, OPERAND_WORD},
	{ INSTRUCTION_ADC_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_08, OPERAND_NONE},
	{ INSTRUCTION_RET_NC, OPERAND_NONE}, /* 0xd0 */
	{ INSTRUCTION_POP_DE, OPERAND_NONE},
	{ INSTRUCTION_JP_NC_U16, OPERAND_WORD},
	{ INSTRUCTION_UNUSED_D3, OPERAND_NONE},
	{ INSTRUCTION_CALL_NC_U16, OPERAND_WORD},
	{ INSTRUCTION_PUSH_DE, OPERAND_NONE},
	{ INSTRUCTION_SUB_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_10, OPERAND_NONE},
	{ INSTRUCTION_RET_C, OPERAND_NONE}, /* 0xd8 */
	{ INSTRUCTION_RETI, OPERAND_NONE},
	{ INSTRUCTION_JP_C_U16, OPERAND_WORD},
	{ INSTRUCTION_UNUSED_DB, OPERAND_NONE},
	{ INSTRUCTION_CALL_C_U16, OPERAND_WORD},
	{ INSTRUCTION_UNUSED_DD, OPERAND_NONE},
	{ INSTRUCTION_SBC_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_18, OPERAND_NONE},
	{ INSTRUCTION_LD_FF00_U8_IND_A, OPERAND_BYTE}, /* 0xe0 */
	{ INSTRUCTION_POP_HL, OPERAND_NONE},
	{ INSTRUCTION_LD_FF00_C_IND_A, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_E3, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_E4, OPERAND_NONE},
	{ INSTRUCTION_PUSH_HL, OPERAND_NONE},
	{ INSTRUCTION_AND_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_20, OPERAND_NONE},
	{ INSTRUCTION_ADD_SP_I8, OPERAND_BYTE}, /* 0xe8 */
	{ INSTRUCTION_JP_HL, OPERAND_NONE},
	{ INSTRUCTION_LD_U16_IND_A, OPERAND_WORD},
	{ INSTRUCTION_UNUSED_EB, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_EC, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_ED, OPERAND_NONE},
	{ INSTRUCTION_XOR_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_28, OPERAND_NONE},
	{ INSTRUCTION_LD_A_FF00_U8_IND, OPERAND_BYTE}, /* 0xf0 */
	{ INSTRUCTION_POP_AF, OPERAND_NONE},
	{ INSTRUCTION_LD_A_FF00_C_IND, OPERAND_NONE},
	{ INSTRUCTION_DI, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_F4, OPERAND_NONE},
	{ INSTRUCTION_PUSH_AF, OPERAND_NONE},
	{ INSTRUCTION_OR_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_30, OPERAND_NONE},
	{ INSTRUCTION_LD_HL_SP_I8, OPERAND_BYTE}, /* 0xf8 */
	{ INSTRUCTION_LD_SP_HL, OPERAND_NONE},
	{ INSTRUCTION_LD_A_U16_IND, OPERAND_WORD},
	{ INSTRUCTION_EI, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_FC, OPERAND_NONE},
	{ INSTRUCTION_UNUSED_FD, OPERAND_NONE},
	{ INSTRUCTION_CP_A_U8, OPERAND_BYTE},
	{ INSTRUCTION_RST_38, OPERAND_NONE},
	};

static const char *INSTRUCTION_STR[] =  {
	"nop", /* 0x00 */
	"ld bc, %04x",
	"ld (bc), a",
	"inc bc",
	"inc b",
	"dec b",
	"ld b, %02x",
	"rlca",
	"ld (%04x), sp", /* 0x08 */
	"add hl, bc",
	"ld a, (bc)",
	"dec bc",
	"inc c",
	"dec c",
	"ld c, %02x",
	"rrca",
	"stop %02x", /* 0x10 */
	"ld de, %04x",
	"ld (de), a",
	"inc de",
	"inc d",
	"dec d",
	"ld d, %02x",
	"rla",
	"jr %02x", /* 0x18 */
	"add hl, de",
	"ld a, (de)",
	"dec de",
	"inc e",
	"dec e",
	"ld e, %02x",
	"rra",
	"jr nz, %02x", /* 0x20 */
	"ld hl, %04x",
	"ld (hl+), a",
	"inc hl",
	"inc h",
	"dec h",
	"ld h, %02x",
	"daa",
	"jr z, %02x", /* 0x28 */
	"add hl, hl",
	"ld a, (hl+)",
	"dec hl",
	"inc l",
	"dec l",
	"ld l, %02x",
	"cpl",
	"jr nc, %02x", /* 0x30 */
	"ld sp, %04x",
	"ld (hl-), a",
	"inc sp",
	"inc (hl)",
	"dec (hl)",
	"ld (hl), %02x",
	"scf",
	"jr c, %02x", /* 0x38 */
	"add hl, sp",
	"ld a, (hl-)",
	"dec sp",
	"inc a",
	"dec a",
	"ld a, %02x",
	"ccf",
	"ld b, b", /* 0x40 */
	"ld b, c",
	"ld b, d",
	"ld b, e",
	"ld b, h",
	"ld b, l",
	"ld b, (hl)",
	"ld b, a",
	"ld c, b", /* 0x40 */
	"ld c, c",
	"ld c, d",
	"ld c, e",
	"ld c, h",
	"ld c, l",
	"ld c, (hl)",
	"ld c, a",
	"ld d, b", /* 0x50 */
	"ld d, c",
	"ld d, d",
	"ld d, e",
	"ld d, h",
	"ld d, l",
	"ld d, (hl)",
	"ld d, a",
	"ld e, b", /* 0x58 */
	"ld e, c",
	"ld e, d",
	"ld e, e",
	"ld e, h",
	"ld e, l",
	"ld e, (hl)",
	"ld e, a",
	"ld h, b", /* 0x60 */
	"ld h, c",
	"ld h, d",
	"ld h, e",
	"ld h, h",
	"ld h, l",
	"ld h, (hl)",
	"ld h, a",
	"ld l, b", /* 0x68 */
	"ld l, c",
	"ld l, d",
	"ld l, e",
	"ld l, h",
	"ld l, l",
	"ld l, (hl)",
	"ld l, a",
	"ld (hl), b", /* 0x70 */
	"ld (hl), c",
	"ld (hl), d",
	"ld (hl), e",
	"ld (hl), h",
	"ld (hl), l",
	"halt",
	"ld (hl), a",
	"ld a, b", /* 0x78 */
	"ld a, c",
	"ld a, d",
	"ld a, e",
	"ld a, h",
	"ld a, l",
	"ld a, (hl)",
	"ld a, a",
	"add a, b", /* 0x80 */
	"add a, c",
	"add a, d",
	"add a, e",
	"add a, h",
	"add a, l",
	"add a, (hl)",
	"add a, a",
	"adc a, b", /* 0x88 */
	"adc a, c",
	"adc a, d",
	"adc a, e",
	"adc a, h",
	"adc a, l",
	"adc a, (hl)",
	"adc a, a",
	"sub a, b", /* 0x90 */
	"sub a, c",
	"sub a, d",
	"sub a, e",
	"sub a, h",
	"sub a, l",
	"sub a, (hl)",
	"sub a, a",
	"sbc a, b", /* 0x98 */
	"sbc a, c",
	"sbc a, d",
	"sbc a, e",
	"sbc a, h",
	"sbc a, l",
	"sbc a, (hl)",
	"sbc a, a",
	"and a, b", /* 0xa0 */
	"and a, c",
	"and a, d",
	"and a, e",
	"and a, h",
	"and a, l",
	"and a, (hl)",
	"and a, a",
	"xor a, b", /* 0xa8 */
	"xor a, c",
	"xor a, d",
	"xor a, e",
	"xor a, h",
	"xor a, l",
	"xor a, (hl)",
	"xor a, a",
	"or a, b", /* 0xb0 */
	"or a, c",
	"or a, d",
	"or a, e",
	"or a, h",
	"or a, l",
	"or a, (hl)",
	"or a, a",
	"cp a, b", /* 0xb8 */
	"cp a, c",
	"cp a, d",
	"cp a, e",
	"cp a, h",
	"cp a, l",
	"cp a, (hl)",
	"cp a, a",
	"ret nz", /* 0xc0 */
	"pop bc",
	"jp nz, %04x",
	"jp %04x",
	"call nz, %04x",
	"push bc",
	"add a, %02x",
	"rst 00",
	"ret z", /* 0xc8 */
	"ret",
	"jp z, %04x",
	"unused",
	"call z, %04x",
	"call %04x",
	"adc a, %02x",
	"rst 08",
	"ret nc", /* 0xd0 */
	"pop de",
	"jp nc, %04x",
	"unused",
	"call nc, %04x",
	"push de",
	"sub a, %02x",
	"rst 10",
	"ret c", /* 0xd8 */
	"reti",
	"jp c, %04x",
	"unused",
	"call c, %04x",
	"unused",
	"sbc a, %02x",
	"rst 18",
	"ld (ff00+%02x), a", /* 0xe0 */
	"pop hl",
	"ld (ff00+c), a",
	"unused",
	"unused",
	"push hl",
	"and a, %02x",
	"rst 20",
	"add sp, %02x", /* 0xe8 */
	"jp hl",
	"ld (%04x), a",
	"unused",
	"unused",
	"unused",
	"xor a, %02x",
	"rst 28",
	"ld a, (ff00+%02x)", /* 0xf0 */
	"pop af",
	"ld a, (ff00+c)",
	"di",
	"unused",
	"push af",
	"or a, %02x",
	"rst 30",
	"ld hl, sp+%02x", /* 0xf8 */
	"ld sp, hl",
	"ld a, (%04x)",
	"ei",
	"unused",
	"unused",
	"cp a, %02x",
	"rst 38",
	};

static const dmg_tool_instruction_t INSTRUCTION_EXTENDED[] = {
	{ INSTRUCTION_EXTENDED_RLC_B, OPERAND_NONE}, /* 0x00 */
	{ INSTRUCTION_EXTENDED_RLC_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RLC_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_B, OPERAND_NONE}, /* 0x08 */
	{ INSTRUCTION_EXTENDED_RRC_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RRC_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_B, OPERAND_NONE}, /* 0x10 */
	{ INSTRUCTION_EXTENDED_RL_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RL_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_B, OPERAND_NONE}, /* 0x18 */
	{ INSTRUCTION_EXTENDED_RR_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RR_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_B, OPERAND_NONE}, /* 0x20 */
	{ INSTRUCTION_EXTENDED_SLA_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SLA_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_B, OPERAND_NONE}, /* 0x28 */
	{ INSTRUCTION_EXTENDED_SRA_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRA_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_B, OPERAND_NONE}, /* 0x30 */
	{ INSTRUCTION_EXTENDED_SWAP_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SWAP_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_B, OPERAND_NONE}, /* 0x38 */
	{ INSTRUCTION_EXTENDED_SRL_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SRL_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_B, OPERAND_NONE}, /* 0x40 */
	{ INSTRUCTION_EXTENDED_BIT_0_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_0_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_B, OPERAND_NONE}, /* 0x48 */
	{ INSTRUCTION_EXTENDED_BIT_1_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_1_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_B, OPERAND_NONE}, /* 0x50 */
	{ INSTRUCTION_EXTENDED_BIT_2_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_2_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_B, OPERAND_NONE}, /* 0x58 */
	{ INSTRUCTION_EXTENDED_BIT_3_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_3_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_B, OPERAND_NONE}, /* 0x60 */
	{ INSTRUCTION_EXTENDED_BIT_4_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_4_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_B, OPERAND_NONE}, /* 0x68 */
	{ INSTRUCTION_EXTENDED_BIT_5_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_5_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_B, OPERAND_NONE}, /* 0x70 */
	{ INSTRUCTION_EXTENDED_BIT_6_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_6_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_B, OPERAND_NONE}, /* 0x78 */
	{ INSTRUCTION_EXTENDED_BIT_7_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_BIT_7_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_B, OPERAND_NONE}, /* 0x80 */
	{ INSTRUCTION_EXTENDED_RES_0_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_0_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_B, OPERAND_NONE}, /* 0x88 */
	{ INSTRUCTION_EXTENDED_RES_1_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_1_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_B, OPERAND_NONE}, /* 0x90 */
	{ INSTRUCTION_EXTENDED_RES_2_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_2_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_B, OPERAND_NONE}, /* 0x98 */
	{ INSTRUCTION_EXTENDED_RES_3_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_3_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_B, OPERAND_NONE}, /* 0xa0 */
	{ INSTRUCTION_EXTENDED_RES_4_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_4_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_B, OPERAND_NONE}, /* 0xa8 */
	{ INSTRUCTION_EXTENDED_RES_5_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_5_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_B, OPERAND_NONE}, /* 0xb0 */
	{ INSTRUCTION_EXTENDED_RES_6_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_6_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_B, OPERAND_NONE}, /* 0xb8 */
	{ INSTRUCTION_EXTENDED_RES_7_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_RES_7_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_B, OPERAND_NONE}, /* 0xc0 */
	{ INSTRUCTION_EXTENDED_SET_0_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_0_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_B, OPERAND_NONE}, /* 0xc8 */
	{ INSTRUCTION_EXTENDED_SET_1_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_1_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_B, OPERAND_NONE}, /* 0xd0 */
	{ INSTRUCTION_EXTENDED_SET_2_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_2_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_B, OPERAND_NONE}, /* 0xd8 */
	{ INSTRUCTION_EXTENDED_SET_3_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_3_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_B, OPERAND_NONE}, /* 0xe0 */
	{ INSTRUCTION_EXTENDED_SET_4_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_4_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_B, OPERAND_NONE}, /* 0xe8 */
	{ INSTRUCTION_EXTENDED_SET_5_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_5_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_B, OPERAND_NONE}, /* 0xf0 */
	{ INSTRUCTION_EXTENDED_SET_6_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_6_A, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_B, OPERAND_NONE}, /* 0xf8 */
	{ INSTRUCTION_EXTENDED_SET_7_C, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_D, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_E, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_H, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_L, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_HL_IND, OPERAND_NONE},
	{ INSTRUCTION_EXTENDED_SET_7_A, OPERAND_NONE},
	};

static const char *INSTRUCTION_EXTENDED_STR[] =  {
	"rlc b", /* 0x00 */
	"rlc c",
	"rlc d",
	"rlc e",
	"rlc h",
	"rlc l",
	"rlc (hl)",
	"rlc a",
	"rrc b", /* 0x08 */
	"rrc c",
	"rrc d",
	"rrc e",
	"rrc h",
	"rrc h",
	"rrc (hl)",
	"rrc a",
	"rl b", /* 0x10 */
	"rl c",
	"rl d",
	"rl e",
	"rl h",
	"rl l",
	"rl (hl)",
	"rl a",
	"rr b", /* 0x18 */
	"rr c",
	"rr d",
	"rr e",
	"rr h",
	"rr l",
	"rr (hl)",
	"rr a",
	"sla b", /* 0x20 */
	"sla c",
	"sla d",
	"sla e",
	"sla h",
	"sla l",
	"sla (hl)",
	"sla a",
	"sra b", /* 0x28 */
	"sra c",
	"sra d",
	"sra e",
	"sra h",
	"sra l",
	"sra (hl)",
	"sra a",
	"swap b", /* 0x30 */
	"swap c",
	"swap d",
	"swap e",
	"swap h",
	"swap l",
	"swap (hl)",
	"swap a",
	"srl b", /* 0x38 */
	"srl c",
	"srl d",
	"srl e",
	"srl h",
	"srl l",
	"srl (hl)",
	"srl a",
	"bit0 b", /* 0x40 */
	"bit0 c",
	"bit0 d",
	"bit0 e",
	"bit0 h",
	"bit0 l",
	"bit0 (hl)",
	"bit0 a",
	"bit1 b", /* 0x48 */
	"bit1 c",
	"bit1 d",
	"bit1 e",
	"bit1 h",
	"bit1 l",
	"bit1 (hl)",
	"bit1 a",
	"bit2 b", /* 0x50 */
	"bit2 c",
	"bit2 d",
	"bit2 e",
	"bit2 h",
	"bit2 l",
	"bit2 (hl)",
	"bit2 a",
	"bit3 b", /* 0x58 */
	"bit3 c",
	"bit3 d",
	"bit3 e",
	"bit3 h",
	"bit3 l",
	"bit3 (hl)",
	"bit3 a",
	"bit4 b", /* 0x60 */
	"bit4 c",
	"bit4 d",
	"bit4 e",
	"bit4 h",
	"bit4 l",
	"bit4 (hl)",
	"bit4 a",
	"bit5 b", /* 0x68 */
	"bit5 c",
	"bit5 d",
	"bit5 e",
	"bit5 h",
	"bit5 l",
	"bit5 (hl)",
	"bit5 a",
	"bit6 b", /* 0x70 */
	"bit6 c",
	"bit6 d",
	"bit6 e",
	"bit6 h",
	"bit6 l",
	"bit6 (hl)",
	"bit6 a",
	"bit7 b", /* 0x78 */
	"bit7 c",
	"bit7 d",
	"bit7 e",
	"bit7 h",
	"bit7 l",
	"bit7 (hl)",
	"bit7 a",
	"res0 b", /* 0x80 */
	"res0 c",
	"res0 d",
	"res0 e",
	"res0 h",
	"res0 l",
	"res0 (hl)",
	"res0 a",
	"res1 b", /* 0x88 */
	"res1 c",
	"res1 d",
	"res1 e",
	"res1 h",
	"res1 l",
	"res1 (hl)",
	"res1 a",
	"res2 b", /* 0x90 */
	"res2 c",
	"res2 d",
	"res2 e",
	"res2 h",
	"res2 l",
	"res2 (hl)",
	"res2 a",
	"res3 b", /* 0x98 */
	"res3 c",
	"res3 d",
	"res3 e",
	"res3 h",
	"res3 l",
	"res3 (hl)",
	"res3 a",
	"res4 b", /* 0xa0 */
	"res4 c",
	"res4 d",
	"res4 e",
	"res4 h",
	"res4 l",
	"res4 (hl)",
	"res4 a",
	"res5 b", /* 0xa8 */
	"res5 c",
	"res5 d",
	"res5 e",
	"res5 h",
	"res5 l",
	"res5 (hl)",
	"res5 a",
	"res6 b", /* 0xb0 */
	"res6 c",
	"res6 d",
	"res6 e",
	"res6 h",
	"res6 l",
	"res6 (hl)",
	"res6 a",
	"res7 b", /* 0xb8 */
	"res7 c",
	"res7 d",
	"res7 e",
	"res7 h",
	"res7 l",
	"res7 (hl)",
	"res7 a",
	"set0 b", /* 0xc0 */
	"set0 c",
	"set0 d",
	"set0 e",
	"set0 h",
	"set0 l",
	"set0 (hl)",
	"set0 a",
	"set1 b", /* 0xc8 */
	"set1 c",
	"set1 d",
	"set1 e",
	"set1 h",
	"set1 l",
	"set1 (hl)",
	"set1 a",
	"set2 b", /* 0xd0 */
	"set2 c",
	"set2 d",
	"set2 e",
	"set2 h",
	"set2 l",
	"set2 (hl)",
	"set2 a",
	"set3 b", /* 0xd8 */
	"set3 c",
	"set3 d",
	"set3 e",
	"set3 h",
	"set3 l",
	"set3 (hl)",
	"set3 a",
	"set4 b", /* 0xe0 */
	"set4 c",
	"set4 d",
	"set4 e",
	"set4 h",
	"set4 l",
	"set4 (hl)",
	"set4 a",
	"set5 b", /* 0xe8 */
	"set5 c",
	"set5 d",
	"set5 e",
	"set5 h",
	"set5 l",
	"set5 (hl)",
	"set5 a",
	"set6 b", /* 0xf0 */
	"set6 c",
	"set6 d",
	"set6 e",
	"set6 h",
	"set6 l",
	"set6 (hl)",
	"set6 a",
	"set7 b", /* 0xf8 */
	"set7 c",
	"set7 d",
	"set7 e",
	"set7 h",
	"set7 l",
	"set7 (hl)",
	"set7 a",
	};

static const char *MAPPER_STR[] = {
	"ROM", /* MAPPER_ROM_ONLY */
	"MBC1", /* MAPPER_MBC1 */
	"MBC1-RAM", /* MAPPER_MBC1_RAM */
	"MBC1-RAM-BATTERY", /* MAPPER_MBC1_RAM_BATTERY */
	"",
	"MBC2", /* MAPPER_MBC2 */
	"MBC2-BATTERY", /* MAPPER_MBC2_BATTERY */
	"",
	"ROM-RAM", /* MAPPER_ROM_RAM */
	"ROM-RAM-BATTERY", /* MAPPER_ROM_RAM_BATTERY */
	"", "", "", "", "",
	"MBC3-TIMER-BATTERY", /* MAPPER_MBC3_TIMER_BATTERY */
	"MBC3-TIMER-RAM-BATTERY", /* MAPPER_MBC3_TIMER_RAM_BATTERY */
	"MBC3", /* MAPPER_MBC3 */
	"MBC3-RAM", /* MAPPER_MBC3_RAM */
	"MBC3-RAM-BATTERY", /* MAPPER_MBC3_RAM_BATTERY */
	"", "", "", "", "",
	"MBC5", /* MAPPER_MBC5 */
	"MBC5-RAM", /* MAPPER_MBC5_RAM */
	"MBC5-RAM-BATTERY", /* MAPPER_MBC5_RAM_BATTERY */
	"MBC5-RUMBLE", /* MAPPER_MBC5_RUMBLE */
	"MBC5-RUMBLE-RAM", /* MAPPER_MBC5_RUMBLE_RAM */
	"MBC5-RUMBLE-RAM-BATTERY", /* MAPPER_MBC5_RUMBLE_RAM_BATTERY */
	};

static const char *RAM_STR[] = {
	"None", /* RAM_NONE */
	"1 bank (2 KB)", /* RAM_2KB */
	"1 bank (8 KB)", /* RAM_8KB */
	"4 banks (32 KB)", /* RAM_32KB */
	"16 banks (128 KB)", /* RAM_128KB */
	};

static const char *ROM_STR[] = {
	"2 banks (32 KB)", /* ROM_32KB */
	"4 banks (64 KB)", /* ROM_64KB */
	"8 banks (128 KB)", /* ROM_128KB */
	"16 banks (256 KB)", /* ROM_256KB */
	"32 banks (512 KB)", /* ROM_512KB */
	"64 banks (1 MB)", /* ROM_1MB */
	"128 banks (2 MB)", /* ROM_2MB */
	"256 banks (4 MB)", /* ROM_4MB */
	"512 banks (8 MB)", /* ROM_8MB */
	};

static const char *VECTOR_STR[] = {
	"vec_rst_00" LABEL_PREFIX, /* VECTOR_RST_00 */
	"vec_rst_08" LABEL_PREFIX, /* VECTOR_RST_08 */
	"vec_rst_10" LABEL_PREFIX, /* VECTOR_RST_10 */
	"vec_rst_18" LABEL_PREFIX, /* VECTOR_RST_18 */
	"vec_rst_20" LABEL_PREFIX, /* VECTOR_RST_20 */
	"vec_rst_28" LABEL_PREFIX, /* VECTOR_RST_28 */
	"vec_rst_30" LABEL_PREFIX, /* VECTOR_RST_30 */
	"vec_rst_38" LABEL_PREFIX, /* VECTOR_RST_38 */
	"vec_vblank" LABEL_PREFIX, /* VECTOR_VBLANK */
	"vec_lcdc" LABEL_PREFIX, /* VECTOR_LCDC */
	"vec_timer" LABEL_PREFIX, /* VECTOR_TIMER */
	"vec_serial" LABEL_PREFIX, /* VECTOR_SERIAL */
	"vec_joypad" LABEL_PREFIX, /* VECTOR_JOYPAD */
	"", /* VECTOR_MAX */
	};

#endif /* DMG_TOOL_SYNTAX_TYPE_H_ */
