/**
 * DMG
 * Copyright (C) 2020-2021 David Jolly
 *
 * DMG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DMG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef DMG_SYSTEM_PROCESSOR_INSTRUCTION_H_
#define DMG_SYSTEM_PROCESSOR_INSTRUCTION_H_

#include "../../common.h"

enum {
	OPERAND_NONE = 0,
	OPERAND_BYTE,
	OPERAND_WORD,
	OPERAND_MAX,
};

typedef struct {
	uint8_t opcode;
	uint8_t operand;
	uint8_t cycle;
	uint8_t cycle_taken;
} dmg_processor_instruction_t;

enum {
	INSTRUCTION_NOP = 0, /* 0x00 */
	INSTRUCTION_LD_BC_U16,
	INSTRUCTION_LD_BC_IND_A,
	INSTRUCTION_INC_BC,
	INSTRUCTION_INC_B,
	INSTRUCTION_DEC_B,
	INSTRUCTION_LD_B_U8,
	INSTRUCTION_RLCA,
	INSTRUCTION_LD_U16_IND_SP, /* 0x08 */
	INSTRUCTION_ADD_HL_BC,
	INSTRUCTION_LD_A_BC_IND,
	INSTRUCTION_DEC_BC,
	INSTRUCTION_INC_C,
	INSTRUCTION_DEC_C,
	INSTRUCTION_LD_C_U8,
	INSTRUCTION_RRCA,
	INSTRUCTION_STOP, /* 0x10 */
	INSTRUCTION_LD_DE_U16,
	INSTRUCTION_LD_DE_IND_A,
	INSTRUCTION_INC_DE,
	INSTRUCTION_INC_D,
	INSTRUCTION_DEC_D,
	INSTRUCTION_LD_D_U8,
	INSTRUCTION_RLA,
	INSTRUCTION_JR_I8, /* 0x18 */
	INSTRUCTION_ADD_HL_DE,
	INSTRUCTION_LD_A_DE_IND,
	INSTRUCTION_DEC_DE,
	INSTRUCTION_INC_E,
	INSTRUCTION_DEC_E,
	INSTRUCTION_LD_E_U8,
	INSTRUCTION_RRA,
	INSTRUCTION_JR_NZ_I8, /* 0x20 */
	INSTRUCTION_LD_HL_U16,
	INSTRUCTION_LD_HL_IND_INC_A,
	INSTRUCTION_INC_HL,
	INSTRUCTION_INC_H,
	INSTRUCTION_DEC_H,
	INSTRUCTION_LD_H_U8,
	INSTRUCTION_DAA,
	INSTRUCTION_JR_Z_I8, /* 0x28 */
	INSTRUCTION_ADD_HL_HL,
	INSTRUCTION_LD_A_HL_IND_INC,
	INSTRUCTION_DEC_HL,
	INSTRUCTION_INC_L,
	INSTRUCTION_DEC_L,
	INSTRUCTION_LD_L_U8,
	INSTRUCTION_CPL,
	INSTRUCTION_JR_NC_I8, /* 0x30 */
	INSTRUCTION_LD_SP_U16,
	INSTRUCTION_LD_HL_IND_DEC_A,
	INSTRUCTION_INC_SP,
	INSTRUCTION_INC_HL_IND,
	INSTRUCTION_DEC_HL_IND,
	INSTRUCTION_LD_HL_IND_U8,
	INSTRUCTION_SCF,
	INSTRUCTION_JR_C_I8, /* 0x38 */
	INSTRUCTION_ADD_HL_SP,
	INSTRUCTION_LD_A_HL_IND_DEC,
	INSTRUCTION_DEC_SP,
	INSTRUCTION_INC_A,
	INSTRUCTION_DEC_A,
	INSTRUCTION_LD_A_U8,
	INSTRUCTION_CCF,
	INSTRUCTION_LD_B_B, /* 0x40 */
	INSTRUCTION_LD_B_C,
	INSTRUCTION_LD_B_D,
	INSTRUCTION_LD_B_E,
	INSTRUCTION_LD_B_H,
	INSTRUCTION_LD_B_L,
	INSTRUCTION_LD_B_HL_IND,
	INSTRUCTION_LD_B_A,
	INSTRUCTION_LD_C_B, /* 0x48 */
	INSTRUCTION_LD_C_C,
	INSTRUCTION_LD_C_D,
	INSTRUCTION_LD_C_E,
	INSTRUCTION_LD_C_H,
	INSTRUCTION_LD_C_L,
	INSTRUCTION_LD_C_HL_IND,
	INSTRUCTION_LD_C_A,
	INSTRUCTION_LD_D_B, /* 0x50 */
	INSTRUCTION_LD_D_C,
	INSTRUCTION_LD_D_D,
	INSTRUCTION_LD_D_E,
	INSTRUCTION_LD_D_H,
	INSTRUCTION_LD_D_L,
	INSTRUCTION_LD_D_HL_IND,
	INSTRUCTION_LD_D_A,
	INSTRUCTION_LD_E_B, /* 0x58 */
	INSTRUCTION_LD_E_C,
	INSTRUCTION_LD_E_D,
	INSTRUCTION_LD_E_E,
	INSTRUCTION_LD_E_H,
	INSTRUCTION_LD_E_L,
	INSTRUCTION_LD_E_HL_IND,
	INSTRUCTION_LD_E_A,
	INSTRUCTION_LD_H_B, /* 0x60 */
	INSTRUCTION_LD_H_C,
	INSTRUCTION_LD_H_D,
	INSTRUCTION_LD_H_E,
	INSTRUCTION_LD_H_H,
	INSTRUCTION_LD_H_L,
	INSTRUCTION_LD_H_HL_IND,
	INSTRUCTION_LD_H_A,
	INSTRUCTION_LD_L_B, /* 0x68 */
	INSTRUCTION_LD_L_C,
	INSTRUCTION_LD_L_D,
	INSTRUCTION_LD_L_E,
	INSTRUCTION_LD_L_H,
	INSTRUCTION_LD_L_L,
	INSTRUCTION_LD_L_HL_IND,
	INSTRUCTION_LD_L_A,
	INSTRUCTION_LD_HL_IND_B, /* 0x70 */
	INSTRUCTION_LD_HL_IND_C,
	INSTRUCTION_LD_HL_IND_D,
	INSTRUCTION_LD_HL_IND_E,
	INSTRUCTION_LD_HL_IND_H,
	INSTRUCTION_LD_HL_IND_L,
	INSTRUCTION_HALT,
	INSTRUCTION_LD_HL_IND_A,
	INSTRUCTION_LD_A_B, /* 0x78 */
	INSTRUCTION_LD_A_C,
	INSTRUCTION_LD_A_D,
	INSTRUCTION_LD_A_E,
	INSTRUCTION_LD_A_H,
	INSTRUCTION_LD_A_L,
	INSTRUCTION_LD_A_HL_IND,
	INSTRUCTION_LD_A_A,
	INSTRUCTION_ADD_B, /* 0x80 */
	INSTRUCTION_ADD_C,
	INSTRUCTION_ADD_D,
	INSTRUCTION_ADD_E,
	INSTRUCTION_ADD_H,
	INSTRUCTION_ADD_L,
	INSTRUCTION_ADD_HL_IND,
	INSTRUCTION_ADD_A,
	INSTRUCTION_ADC_B, /* 0x88 */
	INSTRUCTION_ADC_C,
	INSTRUCTION_ADC_D,
	INSTRUCTION_ADC_E,
	INSTRUCTION_ADC_H,
	INSTRUCTION_ADC_L,
	INSTRUCTION_ADC_HL_IND,
	INSTRUCTION_ADC_A,
	INSTRUCTION_SUB_B, /* 0x90 */
	INSTRUCTION_SUB_C,
	INSTRUCTION_SUB_D,
	INSTRUCTION_SUB_E,
	INSTRUCTION_SUB_H,
	INSTRUCTION_SUB_L,
	INSTRUCTION_SUB_HL_IND,
	INSTRUCTION_SUB_A,
	INSTRUCTION_SBC_B, /* 0x98 */
	INSTRUCTION_SBC_C,
	INSTRUCTION_SBC_D,
	INSTRUCTION_SBC_E,
	INSTRUCTION_SBC_H,
	INSTRUCTION_SBC_L,
	INSTRUCTION_SBC_HL_IND,
	INSTRUCTION_SBC_A,
	INSTRUCTION_AND_B, /* 0xa0 */
	INSTRUCTION_AND_C,
	INSTRUCTION_AND_D,
	INSTRUCTION_AND_E,
	INSTRUCTION_AND_H,
	INSTRUCTION_AND_L,
	INSTRUCTION_AND_HL_IND,
	INSTRUCTION_AND_A,
	INSTRUCTION_XOR_B, /* 0xa8 */
	INSTRUCTION_XOR_C,
	INSTRUCTION_XOR_D,
	INSTRUCTION_XOR_E,
	INSTRUCTION_XOR_H,
	INSTRUCTION_XOR_L,
	INSTRUCTION_XOR_HL_IND,
	INSTRUCTION_XOR_A,
	INSTRUCTION_OR_B, /* 0xb0 */
	INSTRUCTION_OR_C,
	INSTRUCTION_OR_D,
	INSTRUCTION_OR_E,
	INSTRUCTION_OR_H,
	INSTRUCTION_OR_L,
	INSTRUCTION_OR_HL_IND,
	INSTRUCTION_OR_A,
	INSTRUCTION_CP_B, /* 0xb8 */
	INSTRUCTION_CP_C,
	INSTRUCTION_CP_D,
	INSTRUCTION_CP_E,
	INSTRUCTION_CP_H,
	INSTRUCTION_CP_L,
	INSTRUCTION_CP_HL_IND,
	INSTRUCTION_CP_A,
	INSTRUCTION_RET_NZ, /* 0xc0 */
	INSTRUCTION_POP_BC,
	INSTRUCTION_JP_NZ_U16,
	INSTRUCTION_JP_U16,
	INSTRUCTION_CALL_NZ_U16,
	INSTRUCTION_PUSH_BC,
	INSTRUCTION_ADD_U8,
	INSTRUCTION_RST_00,
	INSTRUCTION_RET_Z, /* 0xc8 */
	INSTRUCTION_RET,
	INSTRUCTION_JP_Z_U16,
	INSTRUCTION_EXTENDED_PREFIX,
	INSTRUCTION_CALL_Z_U16,
	INSTRUCTION_CALL_U16,
	INSTRUCTION_ADC_U8,
	INSTRUCTION_RST_08,
	INSTRUCTION_RET_NC, /* 0xd0 */
	INSTRUCTION_POP_DE,
	INSTRUCTION_JP_NC_U16,
	INSTRUCTION_UNUSED_D3,
	INSTRUCTION_CALL_NC_U16,
	INSTRUCTION_PUSH_DE,
	INSTRUCTION_SUB_U8,
	INSTRUCTION_RST_10,
	INSTRUCTION_RET_C, /* 0xd8 */
	INSTRUCTION_RETI,
	INSTRUCTION_JP_C_U16,
	INSTRUCTION_UNUSED_DB,
	INSTRUCTION_CALL_C_U16,
	INSTRUCTION_UNUSED_DD,
	INSTRUCTION_SBC_U8,
	INSTRUCTION_RST_18,
	INSTRUCTION_LD_FF00_U8_IND_A, /* 0xe0 */
	INSTRUCTION_POP_HL,
	INSTRUCTION_LD_FF00_C_IND_A,
	INSTRUCTION_UNUSED_E3,
	INSTRUCTION_UNUSED_E4,
	INSTRUCTION_PUSH_HL,
	INSTRUCTION_AND_U8,
	INSTRUCTION_RST_20,
	INSTRUCTION_ADD_SP_I8, /* 0xe8 */
	INSTRUCTION_JP_HL,
	INSTRUCTION_LD_U16_IND_A,
	INSTRUCTION_UNUSED_EB,
	INSTRUCTION_UNUSED_EC,
	INSTRUCTION_UNUSED_ED,
	INSTRUCTION_XOR_U8,
	INSTRUCTION_RST_28,
	INSTRUCTION_LD_A_FF00_U8_IND, /* 0xf0 */
	INSTRUCTION_POP_AF,
	INSTRUCTION_LD_A_FF00_C_IND,
	INSTRUCTION_DI,
	INSTRUCTION_UNUSED_F4,
	INSTRUCTION_PUSH_AF,
	INSTRUCTION_OR_U8,
	INSTRUCTION_RST_30,
	INSTRUCTION_LD_HL_SP_I8, /* 0xf8 */
	INSTRUCTION_LD_SP_HL,
	INSTRUCTION_LD_A_U16_IND,
	INSTRUCTION_EI,
	INSTRUCTION_UNUSED_FC,
	INSTRUCTION_UNUSED_FD,
	INSTRUCTION_CP_U8,
	INSTRUCTION_RST_38,
	INSTRUCTION_MAX,
};

enum {
	INSTRUCTION_EXTENDED_RLC_B = 0, /* 0x00 */
	INSTRUCTION_EXTENDED_RLC_C,
	INSTRUCTION_EXTENDED_RLC_D,
	INSTRUCTION_EXTENDED_RLC_E,
	INSTRUCTION_EXTENDED_RLC_H,
	INSTRUCTION_EXTENDED_RLC_L,
	INSTRUCTION_EXTENDED_RLC_HL_IND,
	INSTRUCTION_EXTENDED_RLC_A,
	INSTRUCTION_EXTENDED_RRC_B, /* 0x08 */
	INSTRUCTION_EXTENDED_RRC_C,
	INSTRUCTION_EXTENDED_RRC_D,
	INSTRUCTION_EXTENDED_RRC_E,
	INSTRUCTION_EXTENDED_RRC_H,
	INSTRUCTION_EXTENDED_RRC_L,
	INSTRUCTION_EXTENDED_RRC_HL_IND,
	INSTRUCTION_EXTENDED_RRC_A,
	INSTRUCTION_EXTENDED_RL_B, /* 0x10 */
	INSTRUCTION_EXTENDED_RL_C,
	INSTRUCTION_EXTENDED_RL_D,
	INSTRUCTION_EXTENDED_RL_E,
	INSTRUCTION_EXTENDED_RL_H,
	INSTRUCTION_EXTENDED_RL_L,
	INSTRUCTION_EXTENDED_RL_HL_IND,
	INSTRUCTION_EXTENDED_RL_A,
	INSTRUCTION_EXTENDED_RR_B, /* 0x18 */
	INSTRUCTION_EXTENDED_RR_C,
	INSTRUCTION_EXTENDED_RR_D,
	INSTRUCTION_EXTENDED_RR_E,
	INSTRUCTION_EXTENDED_RR_H,
	INSTRUCTION_EXTENDED_RR_L,
	INSTRUCTION_EXTENDED_RR_HL_IND,
	INSTRUCTION_EXTENDED_RR_A,
	INSTRUCTION_EXTENDED_SLA_B, /* 0x20 */
	INSTRUCTION_EXTENDED_SLA_C,
	INSTRUCTION_EXTENDED_SLA_D,
	INSTRUCTION_EXTENDED_SLA_E,
	INSTRUCTION_EXTENDED_SLA_H,
	INSTRUCTION_EXTENDED_SLA_L,
	INSTRUCTION_EXTENDED_SLA_HL_IND,
	INSTRUCTION_EXTENDED_SLA_A,
	INSTRUCTION_EXTENDED_SRA_B, /* 0x28 */
	INSTRUCTION_EXTENDED_SRA_C,
	INSTRUCTION_EXTENDED_SRA_D,
	INSTRUCTION_EXTENDED_SRA_E,
	INSTRUCTION_EXTENDED_SRA_H,
	INSTRUCTION_EXTENDED_SRA_L,
	INSTRUCTION_EXTENDED_SRA_HL_IND,
	INSTRUCTION_EXTENDED_SRA_A,
	INSTRUCTION_EXTENDED_SWAP_B, /* 0x30 */
	INSTRUCTION_EXTENDED_SWAP_C,
	INSTRUCTION_EXTENDED_SWAP_D,
	INSTRUCTION_EXTENDED_SWAP_E,
	INSTRUCTION_EXTENDED_SWAP_H,
	INSTRUCTION_EXTENDED_SWAP_L,
	INSTRUCTION_EXTENDED_SWAP_HL_IND,
	INSTRUCTION_EXTENDED_SWAP_A,
	INSTRUCTION_EXTENDED_SRL_B, /* 0x38 */
	INSTRUCTION_EXTENDED_SRL_C,
	INSTRUCTION_EXTENDED_SRL_D,
	INSTRUCTION_EXTENDED_SRL_E,
	INSTRUCTION_EXTENDED_SRL_H,
	INSTRUCTION_EXTENDED_SRL_L,
	INSTRUCTION_EXTENDED_SRL_HL_IND,
	INSTRUCTION_EXTENDED_SRL_A,
	INSTRUCTION_EXTENDED_BIT_0_B, /* 0x40 */
	INSTRUCTION_EXTENDED_BIT_0_C,
	INSTRUCTION_EXTENDED_BIT_0_D,
	INSTRUCTION_EXTENDED_BIT_0_E,
	INSTRUCTION_EXTENDED_BIT_0_H,
	INSTRUCTION_EXTENDED_BIT_0_L,
	INSTRUCTION_EXTENDED_BIT_0_HL_IND,
	INSTRUCTION_EXTENDED_BIT_0_A,
	INSTRUCTION_EXTENDED_BIT_1_B, /* 0x48 */
	INSTRUCTION_EXTENDED_BIT_1_C,
	INSTRUCTION_EXTENDED_BIT_1_D,
	INSTRUCTION_EXTENDED_BIT_1_E,
	INSTRUCTION_EXTENDED_BIT_1_H,
	INSTRUCTION_EXTENDED_BIT_1_L,
	INSTRUCTION_EXTENDED_BIT_1_HL_IND,
	INSTRUCTION_EXTENDED_BIT_1_A,
	INSTRUCTION_EXTENDED_BIT_2_B, /* 0x50 */
	INSTRUCTION_EXTENDED_BIT_2_C,
	INSTRUCTION_EXTENDED_BIT_2_D,
	INSTRUCTION_EXTENDED_BIT_2_E,
	INSTRUCTION_EXTENDED_BIT_2_H,
	INSTRUCTION_EXTENDED_BIT_2_L,
	INSTRUCTION_EXTENDED_BIT_2_HL_IND,
	INSTRUCTION_EXTENDED_BIT_2_A,
	INSTRUCTION_EXTENDED_BIT_3_B, /* 0x58 */
	INSTRUCTION_EXTENDED_BIT_3_C,
	INSTRUCTION_EXTENDED_BIT_3_D,
	INSTRUCTION_EXTENDED_BIT_3_E,
	INSTRUCTION_EXTENDED_BIT_3_H,
	INSTRUCTION_EXTENDED_BIT_3_L,
	INSTRUCTION_EXTENDED_BIT_3_HL_IND,
	INSTRUCTION_EXTENDED_BIT_3_A,
	INSTRUCTION_EXTENDED_BIT_4_B, /* 0x60 */
	INSTRUCTION_EXTENDED_BIT_4_C,
	INSTRUCTION_EXTENDED_BIT_4_D,
	INSTRUCTION_EXTENDED_BIT_4_E,
	INSTRUCTION_EXTENDED_BIT_4_H,
	INSTRUCTION_EXTENDED_BIT_4_L,
	INSTRUCTION_EXTENDED_BIT_4_HL_IND,
	INSTRUCTION_EXTENDED_BIT_4_A,
	INSTRUCTION_EXTENDED_BIT_5_B, /* 0x68 */
	INSTRUCTION_EXTENDED_BIT_5_C,
	INSTRUCTION_EXTENDED_BIT_5_D,
	INSTRUCTION_EXTENDED_BIT_5_E,
	INSTRUCTION_EXTENDED_BIT_5_H,
	INSTRUCTION_EXTENDED_BIT_5_L,
	INSTRUCTION_EXTENDED_BIT_5_HL_IND,
	INSTRUCTION_EXTENDED_BIT_5_A,
	INSTRUCTION_EXTENDED_BIT_6_B, /* 0x70 */
	INSTRUCTION_EXTENDED_BIT_6_C,
	INSTRUCTION_EXTENDED_BIT_6_D,
	INSTRUCTION_EXTENDED_BIT_6_E,
	INSTRUCTION_EXTENDED_BIT_6_H,
	INSTRUCTION_EXTENDED_BIT_6_L,
	INSTRUCTION_EXTENDED_BIT_6_HL_IND,
	INSTRUCTION_EXTENDED_BIT_6_A,
	INSTRUCTION_EXTENDED_BIT_7_B, /* 0x78 */
	INSTRUCTION_EXTENDED_BIT_7_C,
	INSTRUCTION_EXTENDED_BIT_7_D,
	INSTRUCTION_EXTENDED_BIT_7_E,
	INSTRUCTION_EXTENDED_BIT_7_H,
	INSTRUCTION_EXTENDED_BIT_7_L,
	INSTRUCTION_EXTENDED_BIT_7_HL_IND,
	INSTRUCTION_EXTENDED_BIT_7_A,
	INSTRUCTION_EXTENDED_RES_0_B, /* 0x80 */
	INSTRUCTION_EXTENDED_RES_0_C,
	INSTRUCTION_EXTENDED_RES_0_D,
	INSTRUCTION_EXTENDED_RES_0_E,
	INSTRUCTION_EXTENDED_RES_0_H,
	INSTRUCTION_EXTENDED_RES_0_L,
	INSTRUCTION_EXTENDED_RES_0_HL_IND,
	INSTRUCTION_EXTENDED_RES_0_A,
	INSTRUCTION_EXTENDED_RES_1_B, /* 0x88 */
	INSTRUCTION_EXTENDED_RES_1_C,
	INSTRUCTION_EXTENDED_RES_1_D,
	INSTRUCTION_EXTENDED_RES_1_E,
	INSTRUCTION_EXTENDED_RES_1_H,
	INSTRUCTION_EXTENDED_RES_1_L,
	INSTRUCTION_EXTENDED_RES_1_HL_IND,
	INSTRUCTION_EXTENDED_RES_1_A,
	INSTRUCTION_EXTENDED_RES_2_B, /* 0x90 */
	INSTRUCTION_EXTENDED_RES_2_C,
	INSTRUCTION_EXTENDED_RES_2_D,
	INSTRUCTION_EXTENDED_RES_2_E,
	INSTRUCTION_EXTENDED_RES_2_H,
	INSTRUCTION_EXTENDED_RES_2_L,
	INSTRUCTION_EXTENDED_RES_2_HL_IND,
	INSTRUCTION_EXTENDED_RES_2_A,
	INSTRUCTION_EXTENDED_RES_3_B, /* 0x98 */
	INSTRUCTION_EXTENDED_RES_3_C,
	INSTRUCTION_EXTENDED_RES_3_D,
	INSTRUCTION_EXTENDED_RES_3_E,
	INSTRUCTION_EXTENDED_RES_3_H,
	INSTRUCTION_EXTENDED_RES_3_L,
	INSTRUCTION_EXTENDED_RES_3_HL_IND,
	INSTRUCTION_EXTENDED_RES_3_A,
	INSTRUCTION_EXTENDED_RES_4_B, /* 0xa0 */
	INSTRUCTION_EXTENDED_RES_4_C,
	INSTRUCTION_EXTENDED_RES_4_D,
	INSTRUCTION_EXTENDED_RES_4_E,
	INSTRUCTION_EXTENDED_RES_4_H,
	INSTRUCTION_EXTENDED_RES_4_L,
	INSTRUCTION_EXTENDED_RES_4_HL_IND,
	INSTRUCTION_EXTENDED_RES_4_A,
	INSTRUCTION_EXTENDED_RES_5_B, /* 0xa8 */
	INSTRUCTION_EXTENDED_RES_5_C,
	INSTRUCTION_EXTENDED_RES_5_D,
	INSTRUCTION_EXTENDED_RES_5_E,
	INSTRUCTION_EXTENDED_RES_5_H,
	INSTRUCTION_EXTENDED_RES_5_L,
	INSTRUCTION_EXTENDED_RES_5_HL_IND,
	INSTRUCTION_EXTENDED_RES_5_A,
	INSTRUCTION_EXTENDED_RES_6_B, /* 0xb0 */
	INSTRUCTION_EXTENDED_RES_6_C,
	INSTRUCTION_EXTENDED_RES_6_D,
	INSTRUCTION_EXTENDED_RES_6_E,
	INSTRUCTION_EXTENDED_RES_6_H,
	INSTRUCTION_EXTENDED_RES_6_L,
	INSTRUCTION_EXTENDED_RES_6_HL_IND,
	INSTRUCTION_EXTENDED_RES_6_A,
	INSTRUCTION_EXTENDED_RES_7_B, /* 0xb8 */
	INSTRUCTION_EXTENDED_RES_7_C,
	INSTRUCTION_EXTENDED_RES_7_D,
	INSTRUCTION_EXTENDED_RES_7_E,
	INSTRUCTION_EXTENDED_RES_7_H,
	INSTRUCTION_EXTENDED_RES_7_L,
	INSTRUCTION_EXTENDED_RES_7_HL_IND,
	INSTRUCTION_EXTENDED_RES_7_A,
	INSTRUCTION_EXTENDED_SET_0_B, /* 0xc0 */
	INSTRUCTION_EXTENDED_SET_0_C,
	INSTRUCTION_EXTENDED_SET_0_D,
	INSTRUCTION_EXTENDED_SET_0_E,
	INSTRUCTION_EXTENDED_SET_0_H,
	INSTRUCTION_EXTENDED_SET_0_L,
	INSTRUCTION_EXTENDED_SET_0_HL_IND,
	INSTRUCTION_EXTENDED_SET_0_A,
	INSTRUCTION_EXTENDED_SET_1_B, /* 0xc8 */
	INSTRUCTION_EXTENDED_SET_1_C,
	INSTRUCTION_EXTENDED_SET_1_D,
	INSTRUCTION_EXTENDED_SET_1_E,
	INSTRUCTION_EXTENDED_SET_1_H,
	INSTRUCTION_EXTENDED_SET_1_L,
	INSTRUCTION_EXTENDED_SET_1_HL_IND,
	INSTRUCTION_EXTENDED_SET_1_A,
	INSTRUCTION_EXTENDED_SET_2_B, /* 0xd0 */
	INSTRUCTION_EXTENDED_SET_2_C,
	INSTRUCTION_EXTENDED_SET_2_D,
	INSTRUCTION_EXTENDED_SET_2_E,
	INSTRUCTION_EXTENDED_SET_2_H,
	INSTRUCTION_EXTENDED_SET_2_L,
	INSTRUCTION_EXTENDED_SET_2_HL_IND,
	INSTRUCTION_EXTENDED_SET_2_A,
	INSTRUCTION_EXTENDED_SET_3_B, /* 0xd8 */
	INSTRUCTION_EXTENDED_SET_3_C,
	INSTRUCTION_EXTENDED_SET_3_D,
	INSTRUCTION_EXTENDED_SET_3_E,
	INSTRUCTION_EXTENDED_SET_3_H,
	INSTRUCTION_EXTENDED_SET_3_L,
	INSTRUCTION_EXTENDED_SET_3_HL_IND,
	INSTRUCTION_EXTENDED_SET_3_A,
	INSTRUCTION_EXTENDED_SET_4_B, /* 0xe0 */
	INSTRUCTION_EXTENDED_SET_4_C,
	INSTRUCTION_EXTENDED_SET_4_D,
	INSTRUCTION_EXTENDED_SET_4_E,
	INSTRUCTION_EXTENDED_SET_4_H,
	INSTRUCTION_EXTENDED_SET_4_L,
	INSTRUCTION_EXTENDED_SET_4_HL_IND,
	INSTRUCTION_EXTENDED_SET_4_A,
	INSTRUCTION_EXTENDED_SET_5_B, /* 0xe8 */
	INSTRUCTION_EXTENDED_SET_5_C,
	INSTRUCTION_EXTENDED_SET_5_D,
	INSTRUCTION_EXTENDED_SET_5_E,
	INSTRUCTION_EXTENDED_SET_5_H,
	INSTRUCTION_EXTENDED_SET_5_L,
	INSTRUCTION_EXTENDED_SET_5_HL_IND,
	INSTRUCTION_EXTENDED_SET_5_A,
	INSTRUCTION_EXTENDED_SET_6_B, /* 0xf0 */
	INSTRUCTION_EXTENDED_SET_6_C,
	INSTRUCTION_EXTENDED_SET_6_D,
	INSTRUCTION_EXTENDED_SET_6_E,
	INSTRUCTION_EXTENDED_SET_6_H,
	INSTRUCTION_EXTENDED_SET_6_L,
	INSTRUCTION_EXTENDED_SET_6_HL_IND,
	INSTRUCTION_EXTENDED_SET_6_A,
	INSTRUCTION_EXTENDED_SET_7_B, /* 0xf8 */
	INSTRUCTION_EXTENDED_SET_7_C,
	INSTRUCTION_EXTENDED_SET_7_D,
	INSTRUCTION_EXTENDED_SET_7_E,
	INSTRUCTION_EXTENDED_SET_7_H,
	INSTRUCTION_EXTENDED_SET_7_L,
	INSTRUCTION_EXTENDED_SET_7_HL_IND,
	INSTRUCTION_EXTENDED_SET_7_A,
	INSTRUCTION_EXTENDED_MAX,
};

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

const dmg_processor_instruction_t *dmg_processor_instruction(
	__in uint8_t opcode,
	__in bool extended
	);

const char *dmg_processor_instruction_string(
	__in uint8_t opcode,
	__in bool extended
	);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* DMG_SYSTEM_PROCESSOR_INSTRUCTION_H_ */
