/**
 * DMG
 * Copyright (C) 2020 David Jolly
 *
 * DMG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DMG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef DMG_COMMON_DEFINE_H_
#define DMG_COMMON_DEFINE_H_

#include "../dmg.h"

#ifndef __in
#define __in
#endif /* __in */
#ifndef __inout
#define __inout
#endif /* __inout */
#ifndef __out
#define __out
#endif /* __out */

#define ADDRESS_WIDTH(_BEGIN_, _END_) \
	(((_END_) + 1) - (_BEGIN_))

#define ADDRESS_AUDIO_CONTROL 0xff24
#define ADDRESS_AUDIO_MODE_1_SWEEP 0xff10
#define ADDRESS_AUDIO_MODE_1_LENGTH 0xff11
#define ADDRESS_AUDIO_MODE_1_ENVELOPE 0xff12
#define ADDRESS_AUDIO_MODE_1_FREQUENCY_LOW 0xff13
#define ADDRESS_AUDIO_MODE_1_FREQUENCY_HIGH 0xff14
#define ADDRESS_AUDIO_MODE_2_LENGTH 0xff16
#define ADDRESS_AUDIO_MODE_2_ENVELOPE 0xff17
#define ADDRESS_AUDIO_MODE_2_FREQUENCY_LOW 0xff18
#define ADDRESS_AUDIO_MODE_2_FREQUENCY_HIGH 0xff19
#define ADDRESS_AUDIO_MODE_3_ENABLE 0xff1a
#define ADDRESS_AUDIO_MODE_3_LENGTH 0xff1b
#define ADDRESS_AUDIO_MODE_3_LEVEL 0xff1c
#define ADDRESS_AUDIO_MODE_3_FREQUENCY_LOW 0xff1d
#define ADDRESS_AUDIO_MODE_3_FREQUENCY_HIGH 0xff1e
#define ADDRESS_AUDIO_MODE_4_LENGTH 0xff20
#define ADDRESS_AUDIO_MODE_4_ENVELOPE 0xff21
#define ADDRESS_AUDIO_MODE_4_COUNTER_POLYNOMIAL 0xff22
#define ADDRESS_AUDIO_MODE_4_COUNTER_CONSECUTIVE 0xff23
#define ADDRESS_AUDIO_OUTPUT 0xff25
#define ADDRESS_AUDIO_RAM_BEGIN 0xff30
#define ADDRESS_AUDIO_RAM_END 0xff3f
#define ADDRESS_AUDIO_STATE 0xff26

#define ADDRESS_BOOTROM_BEGIN 0x0000
#define ADDRESS_BOOTROM_DISABLE 0xff50
#define ADDRESS_BOOTROM_END 0x00ff

#define ADDRESS_HEADER_BEGIN 0x0100
#define ADDRESS_HEADER_CHECKSUM_BEGIN 0x0134
#define ADDRESS_HEADER_CHECKSUM_END 0x014c
#define ADDRESS_HEADER_END 0x014f

#define ADDRESS_MBC1_MODE_BEGIN 0x6000
#define ADDRESS_MBC1_MODE_END 0x7fff
#define ADDRESS_MBC1_RAM_ENABLE_BEGIN 0x0000
#define ADDRESS_MBC1_RAM_ENABLE_END 0x1fff
#define ADDRESS_MBC1_ROM_LOWER_BEGIN 0x2000
#define ADDRESS_MBC1_ROM_LOWER_END 0x3fff
#define ADDRESS_MBC1_ROM_UPPER_BEGIN 0x4000
#define ADDRESS_MBC1_ROM_UPPER_END 0x5fff

#define ADDRESS_MBC3_RAM_ENABLE_BEGIN 0x0000
#define ADDRESS_MBC3_RAM_ENABLE_END 0x1fff
#define ADDRESS_MBC3_RAM_BEGIN 0x4000
#define ADDRESS_MBC3_RAM_END 0x5fff
#define ADDRESS_MBC3_ROM_BEGIN 0x2000
#define ADDRESS_MBC3_ROM_END 0x3fff

#define ADDRESS_MBC5_RAM_ENABLE_BEGIN 0x0000
#define ADDRESS_MBC5_RAM_ENABLE_END 0x1fff
#define ADDRESS_MBC5_RAM_BEGIN 0x4000
#define ADDRESS_MBC5_RAM_END 0x5fff
#define ADDRESS_MBC5_ROM_LOWER_BEGIN 0x2000
#define ADDRESS_MBC5_ROM_LOWER_END 0x2fff
#define ADDRESS_MBC5_ROM_UPPER_BEGIN 0x3000
#define ADDRESS_MBC5_ROM_UPPER_END 0x3fff

#define ADDRESS_IO_BASE 0xff00

#define ADDRESS_JOYPAD_STATE 0xff00

#define ADDRESS_PROCESSOR_INTERRUPT_ENABLE 0xffff
#define ADDRESS_PROCESSOR_INTERRUPT_FLAG 0xff0f

#define ADDRESS_RAM_BEGIN 0xc000
#define ADDRESS_RAM_END 0xdfff
#define ADDRESS_RAM_ECHO_BEGIN 0xe000
#define ADDRESS_RAM_ECHO_END 0xfdff
#define ADDRESS_RAM_HIGH_BEGIN 0xff80
#define ADDRESS_RAM_HIGH_END 0xfffe
#define ADDRESS_RAM_SWAP_BEGIN 0xa000
#define ADDRESS_RAM_SWAP_END 0xbfff
#define ADDRESS_RAM_UNUSED_BEGIN 0xfea0
#define ADDRESS_RAM_UNUSED_END 0xfeff

#define ADDRESS_ROM_BEGIN 0x0000
#define ADDRESS_ROM_END 0x3fff
#define ADDRESS_ROM_SWAP_BEGIN 0x4000
#define ADDRESS_ROM_SWAP_END 0x7fff

#define ADDRESS_SERIAL_CONTROL 0xff02
#define ADDRESS_SERIAL_DATA 0xff01

#define ADDRESS_TIMER_CONTROL 0xff07
#define ADDRESS_TIMER_COUNTER 0xff05
#define ADDRESS_TIMER_DIVIDER 0xff04
#define ADDRESS_TIMER_MODULO 0xff06

#define ADDRESS_VIDEO_BACKGROUND_PALETTE 0xff47
#define ADDRESS_VIDEO_CONTROL 0xff40
#define ADDRESS_VIDEO_LINE 0xff44
#define ADDRESS_VIDEO_LINE_COINCIDENCE 0xff45
#define ADDRESS_VIDEO_OBJECT_PALETTE_0 0xff48
#define ADDRESS_VIDEO_OBJECT_PALETTE_1 0xff49
#define ADDRESS_VIDEO_RAM_BEGIN 0x8000
#define ADDRESS_VIDEO_RAM_END 0x9fff
#define ADDRESS_VIDEO_RAM_SPRITE_BEGIN 0xfe00
#define ADDRESS_VIDEO_RAM_SPRITE_END 0xfe9f
#define ADDRESS_VIDEO_SCREEN_X 0xff43
#define ADDRESS_VIDEO_SCREEN_Y 0xff42
#define ADDRESS_VIDEO_STATUS 0xff41
#define ADDRESS_VIDEO_TRANSFER 0xff46
#define ADDRESS_VIDEO_WINDOW_X 0xff4b
#define ADDRESS_VIDEO_WINDOW_Y 0xff4a

#define CYCLE 4

#define NIBBLE_BIT 4
#define NIBBLE_MAX 0x0f

#define VIEWPORT_HEIGHT 144
#define VIEWPORT_WIDTH 160

enum {
	ERROR_SUCCESS = 0,
	ERROR_FAILURE,
	ERROR_INVALID,
	ERROR_MAX,
};

#define ERROR_CLEAR() \
	ERROR_SET(ERROR_SUCCESS, "")

#define ERROR_SET(_ERROR_, _FORMAT_) \
	ERROR_SET_FORMAT(_ERROR_, _FORMAT_, "")
#define ERROR_SET_FORMAT(_ERROR_, _FORMAT_, ...) \
	dmg_error_set(_ERROR_, __FILE__, __FUNCTION__, __LINE__, _FORMAT_, __VA_ARGS__)

enum {
	INTERRUPT_VBLANK = 0,
	INTERRUPT_LCDC,
	INTERRUPT_TIMER,
	INTERRUPT_SERIAL,
	INTERRUPT_JOYPAD,
	INTERRUPT_MAX,
};

enum {
	LEVEL_NONE = 0,
	LEVEL_ERROR,
	LEVEL_WARNING,
	LEVEL_INFORMATION,
	LEVEL_VERBOSE,
	LEVEL_MAX,
};

#define TRACE(_LEVEL_, _FORMAT_) \
	TRACE_FORMAT(_LEVEL_, _FORMAT_, "")
#ifndef NDEBUG
#define TRACE_DISABLE() \
	dmg_trace_enable(false, NULL)
#define TRACE_ENABLE(_CYCLE_) \
	dmg_trace_enable(true, _CYCLE_)
#define TRACE_ERROR(_FORMAT_, _FILE_, _FUNCTION_, _LINE_) \
	if((LEVEL_ERROR) <= (LEVEL)) { \
		dmg_trace(NULL, LEVEL_ERROR, _FILE_, _FUNCTION_, _LINE_, _FORMAT_, ""); \
	}
#define TRACE_FORMAT(_LEVEL_, _FORMAT_, ...) \
	if((_LEVEL_) <= (LEVEL)) { \
		dmg_trace(NULL, _LEVEL_, __FILE__, __FUNCTION__, __LINE__, _FORMAT_, __VA_ARGS__); \
	}
#else
#define TRACE_DISABLE()
#define TRACE_ENABLE(_CYCLE_)
#define TRACE_ERROR(_FORMAT_, _FILE_, _FUNCTION_, _LINE_)
#define TRACE_FORMAT(_LEVEL_, _FORMAT_, ...)
#endif /* NDEBUG */

#endif /* DMG_COMMON_DEFINE_H_ */
