# SPDX-FileCopyrightText: 2023 David Jolly <majestic53@gmail.com>
# SPDX-License-Identifier: MIT

ROOT=../../
SOURCE=src/
TARGET=dmg

SOURCES=$(shell find $(ROOT)src/common/ -name "*.c" -not -name "allocate.c")

include $(ROOT)test/common/Makefile
