name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - name: Build Test
        run: |
          echo $CC
          gcc --version
          make
          make debug LEVEL=4
        env:
          CC: gcc
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev clang
      - name: Build Test
        run: |
          echo $CC
          clang --version
          make
          make debug LEVEL=4
        env:
          CC: clang
