name: Build-All

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Build-GCC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - name: Build
        env:
          CC: gcc
        run:
          echo $CC
          gcc --version
          make
          make debug LEVEL=4
  Build-Clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:
          sudo apt-get update
          sudo apt-get install clang libsdl2-dev
      - name: Build
        env:
          CC: clang
        run:
          echo $CC
          clang --version
          make
          make debug LEVEL=4
